[general]
working_directory = "None"
live_config_reload = true
ipc_socket = true

[window]
dimensions = { columns = 100, lines = 20 }
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.8

[colors.primary]
background = "#000000"

[scrolling]
history = 100000

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
size = 15

[terminal]
shell = "/usr/bin/zsh"
