[general]

working_directory = "None"

live_config_reload = true

ipc_socket = true


[env]


[window]

dimensions = { columns = 120, lines = 20 }

position = { y = 0 }

padding = { x = 10, y = 10 }

decorations = "None"

opacity = 0.9


[scrolling]

history = 100000


[font]

normal = { family = "Hack Nerd Font Mono", style = "Regular" }

size = 12


[terminal]

shell = "/usr/bin/fish"
